name: 'Docker Publish'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-stable:
    name: Docker Publish

    runs-on: ubuntu-latest

    if: ${{ !contains(github.ref, '-') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64'
          push: true
          tags: |
            ttionya/mirai-http:latest
            ttionya/mirai-http:${{ env.TAG }}

  publish-beta:
    name: Docker Publish Beta

    runs-on: ubuntu-latest

    if: ${{ contains(github.ref, '-') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64'
          push: true
          tags: |
            ttionya/mirai-http:${{ env.TAG }}
